application: hd-domain-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
- url: /auth/.*
  script: auth.py
  secure: always
- url: .*
  script: main.app
  secure: always
builtins:
- deferred: on

libraries:
- name: pycrypto
  version: latest
