application: hd-domain
version: 1
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /_km/.*
  script: shared/keymaster.py
  login: admin
- url: .*
  script: main.py
